INSERT INTO "search_patterns" VALUES(1,'Wbc','literal','WBC Leikocīti');
INSERT INTO "search_patterns" VALUES(2,'Neu_perc','literal','NEU% Neitrofīlie leikocīti');
INSERT INTO "search_patterns" VALUES(3,'Neu_abs','literal','NEU# Neitrofīlie leikocīti(abs.sk.)');
INSERT INTO "search_patterns" VALUES(4,'Lym_perc','literal','Lym% Limfocīti');
INSERT INTO "search_patterns" VALUES(5,'Lym_abs','literal','Lym# Limfocīti(abs.sk.)');
INSERT INTO "search_patterns" VALUES(6,'Mon_perc','literal','Mon% Monocīti');
INSERT INTO "search_patterns" VALUES(7,'Mon_abs','literal','Mon# Monocīti(abs.sk.)');
INSERT INTO "search_patterns" VALUES(8,'Eos_perc','literal','EOS% Eozinofīli');
INSERT INTO "search_patterns" VALUES(9,'Eos_abs','literal','EOS Eozinofīli(abs.sk.)');
INSERT INTO "search_patterns" VALUES(10,'Baso_perc','literal','BASO% Bazofīli');
INSERT INTO "search_patterns" VALUES(11,'Baso_abs','literal','BASO Bazofīli(abs.sk.)');
INSERT INTO "search_patterns" VALUES(12,'Ig_proc','literal','IG% Nenobrieduši granulocīti(%)');
INSERT INTO "search_patterns" VALUES(13,'Ig_abs','literal','IG Nenobrieduši granulocīti(abs.sk.');
INSERT INTO "search_patterns" VALUES(14,'Rbc','literal','RBC Eritrocīti');
INSERT INTO "search_patterns" VALUES(15,'Nrbc','literal','NRBC% Kodolsaturošie RBC');
INSERT INTO "search_patterns" VALUES(16,'Nrbc_abs','literal','NRBC# Kodolsaturošo RBC (abs.sk.)');
INSERT INTO "search_patterns" VALUES(17,'Hgb','literal','Hgb Hemoglobīns');
INSERT INTO "search_patterns" VALUES(18,'Hct','literal','Hct Hematokrīts');
INSERT INTO "search_patterns" VALUES(19,'Mcv','literal','MCV Eritrocītu vidējais tilpums');
INSERT INTO "search_patterns" VALUES(20,'Mch','literal','MCH Vidēja Hb saturs eritrocīta');
INSERT INTO "search_patterns" VALUES(21,'Mchc','literal','MCHC Vidējā Hb koncentrācija eritr.');
INSERT INTO "search_patterns" VALUES(22,'Rdw','regexp','RDW +Eritrocītu +anizocitoze(?: +CV)?');
INSERT INTO "search_patterns" VALUES(23,'Plt','literal','Plt Trombocīti');
INSERT INTO "search_patterns" VALUES(24,'Esr','literal','EGĀ (Er. mikrosed. fotometrija)');
INSERT INTO "search_patterns" VALUES(25,'Alt','literal','ALAT');
INSERT INTO "search_patterns" VALUES(26,'Ast','literal','ASAT');
INSERT INTO "search_patterns" VALUES(27,'Alp','regexp','Sārmainā fosf[oa]tāze');
INSERT INTO "search_patterns" VALUES(28,'Ggt','literal','Gamma-glutamil-transferāse');
INSERT INTO "search_patterns" VALUES(29,'Cpk','literal','Kreatīnkināze');
INSERT INTO "search_patterns" VALUES(30,'Creat','literal','Kreatinīns');
INSERT INTO "search_patterns" VALUES(31,'Fbg','literal','Glikoze');
INSERT INTO "search_patterns" VALUES(32,'TotalCholesterol','literal','Kopējais holesterīns');
INSERT INTO "search_patterns" VALUES(33,'Hdlc','literal','ABL-holesterīns');
INSERT INTO "search_patterns" VALUES(34,'Ldlc','literal','ZBL-holesterīns.');
INSERT INTO "search_patterns" VALUES(35,'NonHdlc','regexp','Ne\-ABL[- ]holesterīns');
INSERT INTO "search_patterns" VALUES(36,'Trig','literal','Triglicerīdi');
INSERT INTO "search_patterns" VALUES(37,'Crp','literal','C reaktīvais olbaltums');
INSERT INTO "search_patterns" VALUES(38,'Amy','literal','Alfa amilāze');
INSERT INTO "search_patterns" VALUES(39,'Tsh','regexp','(?:TSH|Tireotropais hormons \(TSH\))');
INSERT INTO "search_patterns" VALUES(40,'25OhD','literal','25-OH-Vit.D Kopējais(D3+D2)');
INSERT INTO "search_patterns" VALUES(41,'urine_Colour','literal','Krāsa');
INSERT INTO "search_patterns" VALUES(42,'urine_SpecGravity','literal','Īpatnējais svars');
INSERT INTO "search_patterns" VALUES(43,'urine_pH','literal','Reakcija');
INSERT INTO "search_patterns" VALUES(44,'urine_Wbc','literal','Leikocīti');
INSERT INTO "search_patterns" VALUES(45,'urine_Nitrites','literal','Nitrīti');
INSERT INTO "search_patterns" VALUES(46,'urine_Protein','literal','Olbaltums');
INSERT INTO "search_patterns" VALUES(47,'urine_Glucose','literal','Glikoze');
INSERT INTO "search_patterns" VALUES(48,'urine_Ketones','literal','Ketonvielas');
INSERT INTO "search_patterns" VALUES(49,'urine_Urobilinogen','literal','Urobilinogēns');
INSERT INTO "search_patterns" VALUES(50,'urine_Bilirubin','literal','Bilirubīns');
INSERT INTO "search_patterns" VALUES(51,'urine_microsc_Wbc','literal','Leikocīti redzes laukā');
INSERT INTO "search_patterns" VALUES(52,'urine_microsc_Squamous','literal','Epitēlijs plakanais redzes laukā');
INSERT INTO "search_patterns" VALUES(53,'Borrelia_IgM','literal','Anti Borrelia burgdorferi IgM');
INSERT INTO "search_patterns" VALUES(54,'stool_Colour','literal','Krāsa');
INSERT INTO "search_patterns" VALUES(55,'stool_Form','literal','Forma');
INSERT INTO "search_patterns" VALUES(56,'stool_pH','literal','Reakcija');
INSERT INTO "search_patterns" VALUES(57,'stool_Fat','literal','Neitrālie tauki');
INSERT INTO "search_patterns" VALUES(58,'stool_OccultBlood','literal','Slēptās asinis');
INSERT INTO "search_patterns" VALUES(59,'stool_FattyAcids','literal','Taukskābes');
INSERT INTO "search_patterns" VALUES(60,'Ggt','literal','Gamma-glutamil-transferāze');
INSERT INTO "search_patterns" VALUES(61,'Psa','literal','Prostatas specifiskais antigēns');
INSERT INTO "search_patterns" VALUES(62,'Tp','literal','Kopējais olbaltums');
INSERT INTO "search_patterns" VALUES(63,'Fe','literal','Dzelzs');
INSERT INTO "search_patterns" VALUES(64,'Ferritin','literal','Ferritīns');
INSERT INTO "search_patterns" VALUES(65,'Tbil','literal','Bilirubīns (kopējais)');
INSERT INTO "search_patterns" VALUES(66,'HBsAg','literal','Hepatīta BsAg');
INSERT INTO "search_patterns" VALUES(67,'AntiHCV','literal','Anti-HCV (Hepatīts C)');
INSERT INTO "search_patterns" VALUES(68,'urine_Rbc','literal','Eritrocīti');
INSERT INTO "search_patterns" VALUES(69,'stool_Intest_Epith','literal','Zarnu epitēlijs redzes laukā');
INSERT INTO "search_patterns" VALUES(70,'stool_Wbc','literal','Leikocīti redzes laukā');
INSERT INTO "search_patterns" VALUES(71,'stool_Rbc','literal','Eritrocīti redzes laukā');
INSERT INTO "search_patterns" VALUES(72,'stool_Mucus','literal','Ģlotas');
INSERT INTO "search_patterns" VALUES(73,'stool_VegFibersIndigest','literal','Stādu barība nesagremojamā');
INSERT INTO "search_patterns" VALUES(74,'stool_VegFibersDigest','literal','Stādu barība sagremojamā');
INSERT INTO "search_patterns" VALUES(75,'stool_MuscleFib','literal','Muskuļu šķiedras neizmainītas');
INSERT INTO "search_patterns" VALUES(76,'stool_MuscleFibPartially','literal','Muskuļu šķiedras izmainītas');
INSERT INTO "search_patterns" VALUES(77,'stool_Soap','literal','Ziepes');
INSERT INTO "search_patterns" VALUES(78,'stool_Starch_InsideCell','literal','Ciete šūnās');
INSERT INTO "search_patterns" VALUES(79,'stool_Starch_OutsideCell','literal','Ciete ārpus šūnām');
INSERT INTO "search_patterns" VALUES(80,'stool_IodophilicFlora','literal','Jodofīlā flora');
INSERT INTO "search_patterns" VALUES(81,'stool_O_P','literal','Parazīti');
INSERT INTO "search_patterns" VALUES(82,'stool_Cyst','literal','Cistas');
INSERT INTO "search_patterns" VALUES(83,'Aptt','literal','APTL');
INSERT INTO "search_patterns" VALUES(84,'Bun','literal','Urea');
INSERT INTO "search_patterns" VALUES(86,'PT_perc','literal','Protrombīna indeks');
INSERT INTO "search_patterns" VALUES(87,'PT_INR','literal','INR');
INSERT INTO "search_patterns" VALUES(88,'Lps','literal','Lipāze');
INSERT INTO "search_patterns" VALUES(89,'Ua','literal','Urīnskābe');
INSERT INTO "search_patterns" VALUES(90,'urine_Mucus','literal','Gļotas');
INSERT INTO "search_patterns" VALUES(91,'urine_Oxalate','literal','Sāļi: Ca oksalāti');
INSERT INTO "search_patterns" VALUES(92,'Calcium','literal','Kalcijs');
INSERT INTO "search_patterns" VALUES(93,'ABO_Group','literal','Asins grupa');
INSERT INTO "search_patterns" VALUES(94,'Rh_Type','literal','Rēzus faktors');
INSERT INTO "search_patterns" VALUES(95,'Gfr','literal','Glomerulu filtrācijas ātrums MRDR');
INSERT INTO "search_patterns" VALUES(96,'urine_Bacteria','literal','Baktērijas');
INSERT INTO "search_patterns" VALUES(97,'Eos_abs','literal','EOS# Eozinofīli(abs.sk.)');
INSERT INTO "search_patterns" VALUES(98,'Rc','literal','Remnantu holesterīns');
INSERT INTO "search_patterns" VALUES(99,'Borrelia_IgG','literal','Anti Borrelia burgdorferi IgG');
INSERT INTO "search_patterns" VALUES(100,'Myoglobin','literal','Mioglobīns');
