INSERT INTO test_classes VALUES(1,'Hematoloģija un anēmiju diagnostika','Hematology',1);
INSERT INTO test_classes VALUES(2,'Koaguloģija','Hemostasis',2);
INSERT INTO test_classes VALUES(3,'Aknu testi un fermenti','Hepatic test and ferment',4);
INSERT INTO test_classes VALUES(4,'Iekaisuma marķieri, autoantivielas','Inflammation markers, autoantibodies',8);
INSERT INTO test_classes VALUES(5,'Slāpekļa vielu maiņa / nieru bioķīmiskie rādītāji','Nitric substance change',5);
INSERT INTO test_classes VALUES(6,'Olbaltumvielas','Protein',6);
INSERT INTO test_classes VALUES(7,'Glikozes regulācija','Glucose regulation',10);
INSERT INTO test_classes VALUES(8,'Lipīdi','Lipids',12);
INSERT INTO test_classes VALUES(9,'Elektrolīti','Electrolytes',11);
INSERT INTO test_classes VALUES(10,'Infekciju diagnostika','Infection diagnostics',16);
INSERT INTO test_classes VALUES(11,'Vairogdziedzera hormoni','Thyreoid gland hormones',14);
INSERT INTO test_classes VALUES(12,'Audzēju marķieri','Tumor markers',19);
INSERT INTO test_classes VALUES(13,'Citi asins izmeklējumi','Other blood tests',17);
INSERT INTO test_classes VALUES(14,'Urīna izmeklējumi','Urine examination',20);
INSERT INTO test_classes VALUES(15,'Fēču izmeklējumi','Stool examination',23);
INSERT INTO test_classes VALUES(16,'Imūnhematoloģija','Immunohematology',3);
INSERT INTO test_classes VALUES(17,'Papildu analīzes','Additional Tests',36);
INSERT INTO test_classes VALUES(18,'Celiakijas diagnostika','Diagnosis of coeliac disease',18);
INSERT INTO test_classes VALUES(19,'Kardioloģiskie marķieri','Cardial markers',7);
INSERT INTO test_classes VALUES(20,'Alerģija','Allergy',NULL);
