INSERT INTO test_names VALUES('Wbc','WBC Leikocīti','WBC White blood cells');
INSERT INTO test_names VALUES('Neu_perc','NEU% Neitrofīlie leikocīti','NEU%');
INSERT INTO test_names VALUES('Neu_abs','NEU# Neitrofīlie leikocīti (abs.sk.)',NULL);
INSERT INTO test_names VALUES('Lym_perc','Lym% Limfocīti',NULL);
INSERT INTO test_names VALUES('Lym_abs','Lym# Limfocīti (abs.sk.)',NULL);
INSERT INTO test_names VALUES('Mon_perc','Mon% Monocīti',NULL);
INSERT INTO test_names VALUES('Mon_abs','Mon# Monocīti (abs.sk.)',NULL);
INSERT INTO test_names VALUES('Eos_perc','EOS% Eozinofīli',NULL);
INSERT INTO test_names VALUES('Eos_abs','EOS Eozinofīli (abs.sk.)',NULL);
INSERT INTO test_names VALUES('Baso_perc','BASO% Bazofīli',NULL);
INSERT INTO test_names VALUES('Baso_abs','BASO Bazofīli (abs.sk.)',NULL);
INSERT INTO test_names VALUES('Ig_proc','IG% Nenobrieduši granulocīti(%)',NULL);
INSERT INTO test_names VALUES('Ig_abs','IG Nenobrieduši granulocīti (abs.sk.)',NULL);
INSERT INTO test_names VALUES('Rbc','RBC Eritrocīti','RBC Red Blood Cells');
INSERT INTO test_names VALUES('Nrbc','NRBC% Kodolsaturošie RBC',NULL);
INSERT INTO test_names VALUES('Nrbc_abs','NRBC# Kodolsaturošo RBC (abs.sk.)',NULL);
INSERT INTO test_names VALUES('Hgb','Hgb Hemoglobīns',NULL);
INSERT INTO test_names VALUES('Hct','Hct Hematokrīts',NULL);
INSERT INTO test_names VALUES('Mcv','MCV Eritrocītu vidējais tilpums',NULL);
INSERT INTO test_names VALUES('Mch','MCH Vidēja Hb saturs eritrocīta',NULL);
INSERT INTO test_names VALUES('Mchc','MCHC Vidējā Hb koncentrācija eritr.',NULL);
INSERT INTO test_names VALUES('Rdw','RDW Eritrocītu anizocitoze CV',NULL);
INSERT INTO test_names VALUES('Plt','Plt Trombocīti','PLT Platelet Count');
INSERT INTO test_names VALUES('Esr','EGĀ (Er. mikrosed. fotometrija)','ESR Erythrocyte Sedimentation Rate');
INSERT INTO test_names VALUES('Alt','ALAT',NULL);
INSERT INTO test_names VALUES('Ast','ASAT',NULL);
INSERT INTO test_names VALUES('Alp','Sārmainā fosfotāze','Alkaline Phosphatase');
INSERT INTO test_names VALUES('Ggt','Gamma-glutamil-transferāze',NULL);
INSERT INTO test_names VALUES('Cpk','Kreatīnkināze',NULL);
INSERT INTO test_names VALUES('Creat','Kreatinīns','Creatinine');
INSERT INTO test_names VALUES('Fbg','Glikoze','Fasting Blood Glucose');
INSERT INTO test_names VALUES('TotalCholesterol','Kopējais holesterīns',NULL);
INSERT INTO test_names VALUES('Hdlc','ABL-holesterīns','High-density Lipoprotein Cholesterol');
INSERT INTO test_names VALUES('Ldlc','ZBL-holesterīns.',NULL);
INSERT INTO test_names VALUES('NonHdlc','Ne-ABL holesterīns','');
INSERT INTO test_names VALUES('Trig','Triglicerīdi',NULL);
INSERT INTO test_names VALUES('Crp','C reaktīvais olbaltums',NULL);
INSERT INTO test_names VALUES('Amy','Alfa amilāze',NULL);
INSERT INTO test_names VALUES('Tsh','TSH',NULL);
INSERT INTO test_names VALUES('25OhD','25-OH-Vit.D Kopējais (D3+D2)',NULL);
INSERT INTO test_names VALUES('urine_Colour','Krāsa',NULL);
INSERT INTO test_names VALUES('urine_SpecGravity','Īpatnējais svars',NULL);
INSERT INTO test_names VALUES('urine_pH','Reakcija',NULL);
INSERT INTO test_names VALUES('urine_Wbc','Leikocīti',NULL);
INSERT INTO test_names VALUES('urine_Nitrites','Nitrīti',NULL);
INSERT INTO test_names VALUES('urine_Protein','Olbaltums',NULL);
INSERT INTO test_names VALUES('urine_Glucose','Glikoze',NULL);
INSERT INTO test_names VALUES('urine_Ketones','Ketonvielas',NULL);
INSERT INTO test_names VALUES('urine_Urobilinogen','Urobilinogēns',NULL);
INSERT INTO test_names VALUES('urine_Bilirubin','Bilirubīns',NULL);
INSERT INTO test_names VALUES('urine_microsc_Squamous','Epitēlijs plakanais redzes laukā',NULL);
INSERT INTO test_names VALUES('urine_microsc_Wbc','Leikocīti redzes laukā',NULL);
INSERT INTO test_names VALUES('stool_Colour','Krāsa','Colour');
INSERT INTO test_names VALUES('stool_Form','Forma','Form');
INSERT INTO test_names VALUES('stool_pH','Reakcija',NULL);
INSERT INTO test_names VALUES('stool_Fat','Neitrālie tauki',NULL);
INSERT INTO test_names VALUES('stool_FattyAcids','Taukskābes',NULL);
INSERT INTO test_names VALUES('stool_OccultBlood','Slēptās asinis',NULL);
INSERT INTO test_names VALUES('Borrelia_IgM','Anti Borrelia burgdorferi IgM',NULL);
INSERT INTO test_names VALUES('Psa','PSA-Prostatas specifiskais antigēns',NULL);
INSERT INTO test_names VALUES('Tp','Kopējais olbaltums','Total Protein');
INSERT INTO test_names VALUES('Fe','Dzelzs','Iron');
INSERT INTO test_names VALUES('Ferritin','Ferritīns',NULL);
INSERT INTO test_names VALUES('Tbil','Bilirubīns (kopējais)','Total Bilirubin');
INSERT INTO test_names VALUES('HBsAg','Hepatīta BsAg',NULL);
INSERT INTO test_names VALUES('AntiHCV','Anti-HCV (Hepatīts C)',NULL);
INSERT INTO test_names VALUES('urine_Rbc','Eritrocīti','Red Blood Cells');
INSERT INTO test_names VALUES('stool_Intest_Epith','Zarnu epitēlijs redzes laukā',NULL);
INSERT INTO test_names VALUES('stool_Wbc','Leikocīti redzes laukā',NULL);
INSERT INTO test_names VALUES('stool_Rbc','Eritrocīti redzes laukā',NULL);
INSERT INTO test_names VALUES('stool_Mucus','Gļotas',NULL);
INSERT INTO test_names VALUES('stool_VegFibersIndigest','Stādu barība nesagremojamā','Vegetable Fibers Indigestible');
INSERT INTO test_names VALUES('stool_VegFibersDigest','Stādu barība sagremojamā','Vegetable Fibers Digestible');
INSERT INTO test_names VALUES('stool_MuscleFib','Muskuļu šķiedras neizmainītas','Muscle Fibers Non-Digested');
INSERT INTO test_names VALUES('stool_MuscleFibPartially','Muskuļu šķiedras izmainītas','Muscle Fibers Partially Digested');
INSERT INTO test_names VALUES('stool_Soap','Ziepes',NULL);
INSERT INTO test_names VALUES('stool_Starch_InsideCell','Ciete šūnās',NULL);
INSERT INTO test_names VALUES('stool_Starch_OutsideCell','Ciete ārpus šūnām',NULL);
INSERT INTO test_names VALUES('stool_IodophilicFlora','Jodofīlā flora',NULL);
INSERT INTO test_names VALUES('stool_O_P','Parazīti','Ova and Parasite');
INSERT INTO test_names VALUES('stool_Cyst','Cistas',NULL);
INSERT INTO test_names VALUES('Aptt','APTL','APTT');
INSERT INTO test_names VALUES('Bun','Urea','Urea Nitrogen');
INSERT INTO test_names VALUES('PT_perc','Protrombīna indeks','Prothrombin Time');
INSERT INTO test_names VALUES('PT_INR','INR',NULL);
INSERT INTO test_names VALUES('Lps','Lipāze','Lipase');
INSERT INTO test_names VALUES('Ua','Urīnskābe','Uric Acid');
INSERT INTO test_names VALUES('urine_Mucus','Gļotas',NULL);
INSERT INTO test_names VALUES('urine_Oxalate','Sāļi: Ca oksalāti','Urine Oxalate');
INSERT INTO test_names VALUES('Calcium','Kalcijs',NULL);
INSERT INTO test_names VALUES('ABO_Group','Asins grupa','Blood Group');
INSERT INTO test_names VALUES('Rh_Type','Rēzus faktors','Rh Factor');
INSERT INTO test_names VALUES('Gfr','Glomerulu filtrācijas ātrums MRDR','Estimated Glomerular Filtration Rate');
INSERT INTO test_names VALUES('urine_Bacteria','Baktērijas',NULL);
INSERT INTO test_names VALUES('Ldh','Laktātdehidrogenāze',NULL);
INSERT INTO test_names VALUES('TbeIgM','Ērču encefalīta vīrusa IgM',NULL);
INSERT INTO test_names VALUES('Borrelia_IgG','Anti Borrelia burgdorferi IgG',NULL);
INSERT INTO test_names VALUES('urine_microsc_Transit','Pārejas epitēlijs',NULL);
INSERT INTO test_names VALUES('urine_HyalineCasts','Hialīnie cilindri',NULL);
INSERT INTO test_names VALUES('urine_Salts','Sāļi',NULL);
INSERT INTO test_names VALUES('TbeIgG','Ērču encefalīta vīrusa anti-IgG',NULL);
INSERT INTO test_names VALUES('Alb','Albumīns',NULL);
INSERT INTO test_names VALUES('Trsf','Transferīns','Transferrin');
INSERT INTO test_names VALUES('Fec','Transferīna piesātinājums','Iron-Binding Capacity');
INSERT INTO test_names VALUES('A1at','α1-antitripsīns','α1-antitrypsin');
INSERT INTO test_names VALUES('TtgaIgA','Transglutamināzes IgA','Transglutaminase IgA');
INSERT INTO test_names VALUES('pAnca','cANCA (PR-3 IgG)','cANCA (PR-3 IgG)');
INSERT INTO test_names VALUES('cAnca','pANCA (MPO IgG)','pANCA (MPO IgG)');
INSERT INTO test_names VALUES('Ana','ANA Antinukleārās antivielas','ANA Antinuclear Antibodies');
INSERT INTO test_names VALUES('Ceruloplasmin','Ceruloplazmīns',NULL);
INSERT INTO test_names VALUES('IgM','Imūnglobulīns M',NULL);
INSERT INTO test_names VALUES('IgA','Imūnglobulīns A',NULL);
INSERT INTO test_names VALUES('IgG','Imūnglobulīns G',NULL);
INSERT INTO test_names VALUES('CytoplasmicA','Citoplazmatiskās antivielas','Cytoplasmic Antibodies');
INSERT INTO test_names VALUES('Na','Nātrijs',NULL);
INSERT INTO test_names VALUES('K','Kālijs',NULL);
INSERT INTO test_names VALUES('Cl','Hlorīdi',NULL);
INSERT INTO test_names VALUES('Fibrinogen','Fibrinogēns',NULL);
INSERT INTO test_names VALUES('Rf','Reimatoīdais faktors','Rheumatoid Factor');
INSERT INTO test_names VALUES('Phosphate','Fosfors',NULL);
INSERT INTO test_names VALUES('FT4','T4 brīvais tiroksīns',NULL);
INSERT INTO test_names VALUES('Hiv12Ab1Ag','Anti-HIV-1/-2, Ag p24',NULL);
INSERT INTO test_names VALUES('Rc','Remnantu holesterīns','Remnant cholesterol');
INSERT INTO test_names VALUES('Myoglobin','Mioglobīns',NULL);
INSERT INTO test_names VALUES('B12','Vitamīns B12','Vitamin B12');
INSERT INTO test_names VALUES('VzvIgG','Varicella zoster vīrusa IgG','Varicella Zoster Virus IgG');
INSERT INTO test_names VALUES('VzvIgM','Varicella zoster vīrusa IgM','Varicella Zoster Virus IgM');
INSERT INTO test_names VALUES('EbvVcaIgG','Epšteina-Barra vīrusa VCA IgG','Epstein-Barr Virus Antibody to VCA, IgG');
INSERT INTO test_names VALUES('EbvVcaIgM','Epšteina-Barra vīrusa VCA IgM','Epstein-Barr Virus Antibody to VCA, IgM');
INSERT INTO test_names VALUES('CmvIgG','Citomegalovīrusa IgG','Cytomegalovirus, IgG');
INSERT INTO test_names VALUES('CmvIgM','Citomegalovīrusa IgM','Cytomegalovirus, IgM');
INSERT INTO test_names VALUES('Aso','Antistreptolizīns O','Antistreptolysin-O');
INSERT INTO test_names VALUES('HPyloriIgG','Helicobacter Pylori IgG','Helicobacter Pylori IgG');
INSERT INTO test_names VALUES('HPyloriIgA','Helicobacter Pylori IgA','Helicobacter Pylori IgA');
INSERT INTO test_names VALUES('Allergen_IgG4_fx11','Sieri (fx11) (IgG4)','Cheese (fx11) (IgG4)');
INSERT INTO test_names VALUES('Allergen_IgG4_f79','Glutēns (f79) (IgG4)','Gluten (f79) (IgG4)');
INSERT INTO test_names VALUES('urine_microsc_Rbc','Eritrocīti redzes laukā',NULL);
INSERT INTO test_names VALUES('Allergen_IgG4_f12','Zirņi (f12) (IgG4)','Peas (f12) (IgG4)');
INSERT INTO test_names VALUES('Allergen_IgG4_f13','Zemesrieksti (f13) (IgG4)','Peanuts (f13) (IgG4)');
INSERT INTO test_names VALUES('Allergen_IgG4_f36','Kokosrieksti (f36) (IgG4)','Coconuts (f36) (IgG4)');
INSERT INTO test_names VALUES('Allergen_IgG4_f3','Menca (f3) (IgG4)','Cod (f3) (IgG4)');
INSERT INTO test_names VALUES('Allergen_IgG4_f41','Lasis (f41) (IgG4)','Salmon (f41) (IgG4)');
INSERT INTO test_names VALUES('Allergen_IgG4_f11','Griķi (f11) (IgG4)','Buckweat (f11) (IgG4)');
INSERT INTO test_names VALUES('Allergen_IgG4_f7','Auzu milti (f7) (IgG4)','Oat flour (f7) (IgG4)');
INSERT INTO test_names VALUES('Allergen_IgG4_f8','Kukurūzas milti (f8) (IgG4)','Corn flour (f8) (IgG4)');
INSERT INTO test_names VALUES('Allergen_IgG4_f31','Burkāni (f31) (IgG4)','Carrots (f31) (IgG4)');
INSERT INTO test_names VALUES('Allergen_IgG4_f85','Selerijas (f85) (IgG4)','Celery (f85) (IgG4)');
INSERT INTO test_names VALUES('Allergen_IgG4_f49','Āboli (f49) (IgG4)','Apples (f49) (IgG4)');
INSERT INTO test_names VALUES('Allergen_IgG4_f33','Apelsīni (f33) (IgG4)','Oranges (f33) (IgG4)');
INSERT INTO test_names VALUES('Allergen_IgG4_f26','Cūkas gaļa (f26) (IgG4)','Pork (f26) (IgG4)');
INSERT INTO test_names VALUES('Allergen_IgG4_f27','Liellopu gaļa (f27) (IgG4)','Beef (f27) (IgG4)');
INSERT INTO test_names VALUES('Allergen_IgG4_f83','Vistas gaļa (f83) (IgG4)','Chicken (f83) (IgG4)');
INSERT INTO test_names VALUES('Allergen_IgG4_f35','Kartupeļi (f35) (IgG4)','Potatoes (f35) (IgG4)');
INSERT INTO test_names VALUES('Allergen_IgG4_f4','Kviešu milti (f4) (IgG4)','Wheat flour (f4) (IgG4)');
INSERT INTO test_names VALUES('Allergen_IgG4_f5','Rudzu milti (f5) (IgG4)','Rye flour (f5) (IgG4)');
INSERT INTO test_names VALUES('Allergen_IgG4_f25','Tomāti (f25) (IgG4)','Tomatoes (f25) (IgG4)');
INSERT INTO test_names VALUES('Allergen_IgG4_f218','Saldie pipari (f218) (IgG4)','Sweet pepper (f218) (IgG4)');
INSERT INTO test_names VALUES('Allergen_IgG4_f92','Banāni (f92) (IgG4)','Bananas (f92) (IgG4)');
INSERT INTO test_names VALUES('Allergen_IgG4_f1','Olas baltums (f1) (IgG4)','Egg white (f1) (IgG4)');
INSERT INTO test_names VALUES('Allergen_IgG4_f75','Olas dzeltenums (f75) (IgG4)','Egg yolk (f75) (IgG4)');
INSERT INTO test_names VALUES('Allergen_IgG4_f2','Piens (f2) (IgG4)','Milk (f2) (IgG4)');
INSERT INTO test_names VALUES('Allergen_IgG4_f76','Alfa-laktoalbumīns (f76) (IgG4)','α-lactalbumin (f76) (IgG4)');
INSERT INTO test_names VALUES('Allergen_IgG4_f77','Beta-laktoglobulīns (f77) (IgG4)','β-lactoglobulin (f77) (IgG4)');
INSERT INTO test_names VALUES('Allergen_IgG4_f78','Kazeīns (f78) (IgG4)','Casein (f78) (IgG4)');
INSERT INTO test_names VALUES('Allergen_IgG4_f14','Sojas pupiņas (f14) (IgG4)','Soya beans (f14) (IgG4)');
INSERT INTO test_names VALUES('Mpv','MPV Vidējais trombocītu tilpums','Mean Platelet Volume');
INSERT INTO test_names VALUES('Ena','ENA skrīnings','Extractable Nuclear Antigen');
INSERT INTO test_names VALUES('IgE','Imūnglobulīns E',NULL);
INSERT INTO test_names VALUES('CD3_perc','CD3 %',NULL);
INSERT INTO test_names VALUES('CD4_perc','CD4 %',NULL);
INSERT INTO test_names VALUES('CD8_perc','CD8 %',NULL);
INSERT INTO test_names VALUES('CD4_CD8_ratio','CD4/CD8 indekss',NULL);
INSERT INTO test_names VALUES('CD16_perc','CD16 %',NULL);
INSERT INTO test_names VALUES('CD19_perc','CD19 %',NULL);
INSERT INTO test_names VALUES('CD25_perc','CD25 %',NULL);
